### ISSUE TITLE
Fail when downloading to public location on api 28+

### ISSUE THREAD

**Issue by Slavrix** [Luka313/integrator-cordova-plugin-downloader#12]
When trying to download to public folders using 
```
      destinationInExternalPublicDir: {
        dirType: this.file.externalRootDirectory + "Download/",
        subPath: this.randomStr() + '_' + saveTitle
      }
```
java.lang.IllegalStateException: Not one of standard directories: file:///storage/emulated/0/Download/
is the error returned.

Downloading to the app storage works fine.

**Comment by akk7777** [comment]
@Slavrix getting same error. How did you solve this? i have tried multiple workarounds but still getting same error.

Thanks
