### ISSUE TITLE
Can not find module @ionic-native/downloader/ngx

### ISSUE THREAD

**Issue by supriyakhankar** [Luka313/integrator-cordova-plugin-downloader#2]
I added this package to my ionic 3 project using below 2 commands:
1 - ionic cordova plugin add integrator-cordova-plugin-downloader
2 - npm install --save @ionic-native/downloader

When I am trying to import Downloader to my project. I am getting error 
Can not find module @ionic-native/downloader/ngx
Please help.

**Comment by Luka313** [comment]
For Ionic 3 projects you should import module like this:

`import { Downloader } from '@ionic-native/downloader';`
 
I just realized its a mistake in the Ionic 3 documentation. Sorry for that.

**Comment by supriyakhankar** [comment]
Thanks for the reply. Previously i tired 
import { Downloader } from '@ionic-native/downloader'; 
this also. But was getting error can not find modules DownloadRequest and NotificationVisibility. So correct way to import downloader is

import { Downloader ,DownloadRequest ,NotificationVisibility} from '@ionic-native/downloader';

**Comment by supriyakhankar** [comment]
Closing this issue.. thanks for quick help
